import type { Metadata } from "next";
import { SiteFooter } from "@/components/layout/site-footer";
import { SiteHeader } from "@/components/layout/site-header";
import styles from "../legal.module.css";

export const metadata: Metadata = { title: "Terms of use" };
const sections=["Screening only","Using SoundCue","Accounts and recordings","Availability","Limits","Contact"];
export default function TermsPage(){return <><SiteHeader /><main id="main-content" className={`${styles.legal} page-container`}><header><p className={styles.eyebrow}>Terms</p><h1>Terms for a careful screening tool.</h1><p className={styles.intro}>These terms set clear boundaries for the SoundCue research screening service.</p><p className={styles.updated}>Research model draft · Updated August 8, 2026</p></header><div className={styles.content}><nav className={styles.toc} aria-label="On this page"><strong>On this page</strong>{sections.map((s)=><a href={`#${s.toLowerCase().replaceAll(" ","-")}`} key={s}>{s}</a>)}</nav><div className={styles.sections}>
<p className={styles.notice}><strong>Review before public launch</strong>These terms and the patient-facing research screening use require final legal and regulatory review before public access is enabled.</p>
<section id="screening-only"><h2>Screening only—not medical advice or a diagnosis</h2><p>SoundCue is intended to help identify voice patterns that may be worth discussing with a healthcare professional. It cannot diagnose, confirm, exclude, monitor, or treat Parkinson&apos;s disease or any other condition. A result must not replace a clinician&apos;s evaluation, and you should not delay care because of it.</p><p>If you are worried about symptoms, contact a qualified healthcare professional. For an emergency, call local emergency services.</p></section>
<section id="using-soundcue"><h2>Using SoundCue</h2><p>You must be 18 to 85 years old, be able to consent to these terms and the current screening consent, and provide your whole-number age for each screening. Provide only your own voice unless you are legally authorized to act for another person. Use a compatible browser and a quiet, safe place; never record while driving or doing something that needs your attention.</p><p>Do not misuse the service, attempt to access another account, evade limits, upload harmful material, reverse engineer protected services, or use a screening result to make a diagnosis or treatment decision.</p></section>
<section id="accounts-and-recordings"><h2>Accounts and recordings</h2><p>You are responsible for safeguarding your password and device. Tell us promptly if you believe your account is compromised. You keep rights in your recording and give SoundCue permission to process and store it only as needed to provide and secure the service under the Privacy Notice.</p><p>You can delete individual screenings or your entire account. Deletion is permanent once completed.</p></section>
<section id="availability"><h2>Research availability and changes</h2><p>SoundCue may be changed, paused, or withdrawn while it is evaluated. The deployed three-component research model combines three audio-analysis views with age and compares its output with an internal 81-participant development reference. It has not been independently validated, its development data had age imbalance, and its categories are not probabilities or clinical risk estimates.</p><p>Features, consent text, retention practices, preprocessing, band policies, and research-model versions may change. SoundCue requests renewed consent when the consent document changes and does not connect trends across incompatible band-policy versions.</p></section>
<section id="limits"><h2>Limits and responsibility</h2><p>To the extent permitted by law, the beta is provided without warranties of uninterrupted availability, clinical accuracy, fitness for a particular purpose, or error-free operation. Nothing in these terms excludes rights or responsibilities that cannot lawfully be excluded. Final limitation, governing-law, and dispute provisions require counsel approval before public launch.</p></section>
<section id="contact"><h2>Contact</h2><p>Questions about these terms can be sent to <a className="text-link" href="mailto:support@soundcue.health">support@soundcue.health</a>. This address must be confirmed before public launch.</p></section>
</div></div></main><SiteFooter /></>}
