import type { Metadata } from "next";
import { SiteFooter } from "@/components/layout/site-footer";
import { SiteHeader } from "@/components/layout/site-header";
import styles from "../legal.module.css";

export const metadata: Metadata = { title: "Privacy notice" };
const sections = ["Information we collect","How we use it","Storage and retention","Your choices","Security and service providers","Contact"];

export default function PrivacyPage(){return <><SiteHeader /><main id="main-content" className={`${styles.legal} page-container`}><header><p className={styles.eyebrow}>Privacy</p><h1>Your voice is personal.</h1><p className={styles.intro}>This notice explains what SoundCue collects for the Parkinson’s voice screening experience, why it is needed, and how you can remove it.</p><p className={styles.updated}>Research model draft · Updated August 8, 2026</p></header><div className={styles.content}><nav className={styles.toc} aria-label="On this page"><strong>On this page</strong>{sections.map((section)=><a href={`#${section.toLowerCase().replaceAll(" ","-")}`} key={section}>{section}</a>)}</nav><div className={styles.sections}>
<p className={styles.notice}><strong>Review before public launch</strong>This privacy notice is product copy for the beta implementation and must receive final privacy counsel approval before public signup is enabled.</p>
<section id="information-we-collect"><h2>Information we collect</h2><p>We collect the email address and account identifiers needed to create and protect your account; the consent version and time you agreed; your sound-cue preference; and information from each screening.</p><p>A screening includes your private voice recording, your whole-number age at the time of that screening, recording duration and format, recording-quality measurements, server-derived acoustic observations, encoder representations, research-model versions, the relative pattern category, reviewed observation codes, and creation times. Age belongs to that screening and is not added to a reusable profile. We do not collect sex, a diagnosis, or a medical record for this analysis.</p></section>
<section id="how-we-use-it"><h2>How we use information</h2><p>We use your recording and age together to run three Parkinson’s voice research-model analysis views, provide the screening result, show comparable history, and create individual and trend-based clinician reports. We also use account information to provide authentication, retained playback, consent records, deletion, abuse prevention, and safe operation of the service.</p><p>The web server sends the recording and age through an authenticated, tamper-checked request to SoundCue&apos;s protected Python inference service. The service decodes and standardizes the recording, creates temporary encoder representations, and returns model and quality outputs. Requests are not accepted directly from a browser. Intermediate representations are used for that analysis and are not exposed in your account.</p><p>SoundCue does not use third-party behavioral advertising or sell personal information. Operational logs use request identifiers, timing, model version, status, and coarse error codes; they are designed not to contain audio, email addresses, access tokens, acoustic features, result values, storage paths, or PDF contents.</p></section>
<section id="storage-and-retention"><h2>Storage and retention</h2><p>Recordings are stored in a private bucket and are retrieved through an authenticated request. Account and screening records are stored in a database in the United States. During this beta, a recording and its screening are retained until you delete that screening or permanently delete your account, unless a shorter period is required by law or a security event.</p><p>Deleting an individual screening removes its recording first and then its screening record. Deleting your account removes retained recordings, screening results, preferences, consent records, and authentication account. Limited security or backup records may persist temporarily until routine backup rotation completes.</p></section>
<section id="your-choices"><h2>Your choices</h2><ul><li>Turn optional sound cues off while keeping visual guidance.</li><li>Listen to and delete an individual retained recording from your history.</li><li>Download a clinician-oriented summary.</li><li>Delete your account permanently from Settings after recent authentication.</li></ul><p>You can choose not to record. SoundCue is optional and is not emergency care.</p></section>
<section id="security-and-service-providers"><h2>Security and service providers</h2><p>We use access controls, private object storage, encrypted transport, ownership checks, signed inference requests, restrictive browser headers, schema validation, and database-backed rate limits. Model scores and component outputs are restricted to trusted server access. No online service can guarantee absolute security.</p><p>SoundCue uses Supabase for authentication, database, and private storage, and Vercel for the web application and protected Python inference service. Configuration alone does not make SoundCue HIPAA compliant, and we do not claim that it is. Appropriate contracts and organizational controls would be required if SoundCue later handles protected health information on behalf of a covered entity or business associate.</p></section>
<section id="contact"><h2>Contact</h2><p>Questions, privacy requests, and accessibility support can be sent to <a className="text-link" href="mailto:privacy@soundcue.health">privacy@soundcue.health</a>. This address must be confirmed before public launch.</p></section>
</div></div></main><SiteFooter /></>}
