import type { Metadata } from "next";
import { SiteFooter } from "@/components/layout/site-footer";
import { SiteHeader } from "@/components/layout/site-header";
import styles from "../legal.module.css";

export const metadata: Metadata = { title: "Accessibility" };
const sections=["Our commitment","What is supported","Known limitations","Feedback"];
export default function AccessibilityPage(){return <><SiteHeader /><main id="main-content" className={`${styles.legal} page-container`}><header><p className={styles.eyebrow}>Accessibility</p><h1>A calm experience should be an accessible one.</h1><p className={styles.intro}>SoundCue is designed for different ways of seeing, hearing, moving, and using the web.</p><p className={styles.updated}>Accessibility statement · Updated August 6, 2026</p></header><div className={styles.content}><nav className={styles.toc} aria-label="On this page"><strong>On this page</strong>{sections.map((s)=><a href={`#${s.toLowerCase().replaceAll(" ","-")}`} key={s}>{s}</a>)}</nav><div className={styles.sections}>
<section id="our-commitment"><h2>Our commitment</h2><p>Our target is WCAG 2.2 Level AA. We evaluate the core flow with automated checks and manual keyboard, screen-reader, zoom, reduced-motion, sound-off, and color-independence reviews. Accessibility is part of release acceptance, not a later add-on.</p></section>
<section id="what-is-supported"><h2>What is supported</h2><ul><li>Readable 18-pixel-oriented text, strong contrast, and responsive layouts.</li><li>Keyboard-operable controls with visible focus and touch targets at least 44 by 44 pixels.</li><li>Landmarks, headings, labels, status announcements, and descriptions for charts and waveform states.</li><li>Recording countdown, start, stop, and microphone warnings shown visually as well as through optional sound cues.</li><li>Risk charts that use words, position, and shapes—not color alone.</li><li>Reduced-motion behavior that removes non-essential transitions and animation.</li><li>Plain-language reminders that SoundCue is a screening aid, not a diagnosis.</li></ul></section>
<section id="known-limitations"><h2>Known limitations</h2><p>Browser microphone permission dialogs are controlled by the browser and operating system, so their keyboard and screen-reader behavior can vary. Audio recording formats also differ by browser. We provide clear recovery guidance when a format or permission is unavailable.</p><p>The public beta must complete testing in current Chrome, Edge, Safari/WebKit, and Firefox before public signup is enabled.</p></section>
<section id="feedback"><h2>Feedback and help</h2><p>If something prevents you from completing a screening, tell us what page you were on, the browser or assistive technology you used, and what you expected to happen. Email <a className="text-link" href="mailto:accessibility@soundcue.health">accessibility@soundcue.health</a>. This address must be confirmed before public launch.</p></section>
</div></div></main><SiteFooter /></>}
